version: "3.9"

# vars used in this docker-compose are specified in .env file
services:
  database:
    image: postgres:14.4
    container_name: slackbot-db
    ports:
      - ${POSTGRES_PORT}:5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      start_period: 5s
      test: pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}
      interval: 3s
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - database
    env_file:
      - .env
    pull_policy: always
