// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// GithubUsersColumns holds the columns for the "github_users" table.
	GithubUsersColumns = []*schema.Column{
		{Name: "id", Type: field.TypeUUID},
		{Name: "gh_username", Type: field.TypeString},
		{Name: "slack_id", Type: field.TypeString, Unique: true},
		{Name: "gh_access_token", Type: field.TypeString},
		{Name: "created_at", Type: field.TypeTime},
		{Name: "updated_at", Type: field.TypeTime},
	}
	// GithubUsersTable holds the schema information for the "github_users" table.
	GithubUsersTable = &schema.Table{
		Name:       "github_users",
		Columns:    GithubUsersColumns,
		PrimaryKey: []*schema.Column{GithubUsersColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		GithubUsersTable,
	}
)

func init() {
}
