// Code generated by ent, DO NOT EDIT.

package predicate

import (
	"entgo.io/ent/dialect/sql"
)

// GithubUser is the predicate function for githubuser builders.
type GithubUser func(*sql.Selector)
